In [2]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.datasets import make_blobs
import logging
logging.getLogger("tensorflow").setLevel(logging.ERROR)
tf.autograph.set_verbosity(0)

## Tensorflow

In [3]:
centers = [[-5, 2], [-2, -2], [1, 2], [5, -2]]
x_train, y_train = make_blobs(n_samples = 2000, centers = centers, cluster_std = 1.0, random_state = 30)

In [4]:
model = Sequential([
    Dense(units = 25, activation = 'relu'),
    Dense(units = 15, activation = 'relu'),
    Dense(units = 4, activation = 'softmax')
])
model.compile(
    loss = tf.keras.losses.SparseCategoricalCrossentropy(),
    optimizer = tf.keras.optimizers.Adam(0.001)
)
model.fit(x_train, y_train, epochs = 10)

Epoch 1/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 1.0732
Epoch 2/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.4988
Epoch 3/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.1985
Epoch 4/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.1106
Epoch 5/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.0754
Epoch 6/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.0606
Epoch 7/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.0527
Epoch 8/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.0473
Epoch 9/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.0427
Epoch 10/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.0386


In [5]:
p_nonpreferred = model.predict(x_train)
print(p_nonpreferred[:2])
print("Largest value: ", np.max(p_nonpreferred), "Smallest value: ", np.min(p_nonpreferred))

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
[[1.7174050e-03 6.7558489e-04 9.8656392e-01 1.1043019e-02]
 [9.9515682e-01 4.0522916e-03 6.7613437e-04 1.1479116e-04]]
Largest value:  0.99999845 Smallest value:  2.502326e-09


## Preferred

In [7]:
preferred_model = Sequential([
    Dense(units = 25, activation = 'relu'),
    Dense(units = 15, activation = 'relu'),
    Dense(units = 4, activation = 'linear')
])

preferred_model.compile(
    loss = tf.keras.losses.SparseCategoricalCrossentropy(from_logits = True),
    optimizer = tf.keras.optimizers.Adam(0.001)
)

preferred_model.fit(x_train, y_train, epochs = 10)

Epoch 1/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 1.0780
Epoch 2/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.4131
Epoch 3/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.1829
Epoch 4/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1117
Epoch 5/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.0832
Epoch 6/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.0690
Epoch 7/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.0601
Epoch 8/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 0.0543
Epoch 9/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.0501
Epoch 10/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.0465


In [9]:
p_preferred = preferred_model.predict(x_train)
print(f"Two example output vectors:\n {p_preferred[:2]}")
print("Largest value: ", np.max(p_preferred), "Smallest value: ", np.min(p_preferred))

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
Two example output vectors:
 [[-1.9501752  -1.8502373   2.821753   -0.7753908 ]
 [ 6.12058     0.61865604 -4.606075   -8.187067  ]]
Largest value:  9.716999 Smallest value:  -11.99443


In [10]:
sm_preferred = tf.nn.softmax(p_preferred).numpy()
print(f"Two example output vectors:\n{sm_preferred[:2]}")
print("Largest value: ", np.max(sm_preferred), "Smallest value: ", np.min(sm_preferred))

Two example output vectors:
[[8.0978600e-03 8.9489641e-03 9.5673668e-01 2.6216377e-02]
 [9.9591523e-01 4.0622544e-03 2.1862274e-05 6.0882149e-07]]
Largest value:  0.99999917 Smallest value:  5.1310567e-10


In [11]:
for i in range(5):
    print(f"{p_preferred[i]}, category: {np.argmax(p_preferred[i])}")

[-1.9501752 -1.8502373  2.821753  -0.7753908], category: 2
[ 6.12058     0.61865604 -4.606075   -8.187067  ], category: 0
[ 4.4209666  0.7043481 -3.5393877 -6.655483 ], category: 0
[-2.4427657  3.5133305 -2.993439  -3.278787 ], category: 1
[-0.79261744 -3.289452    5.096808   -3.019967  ], category: 2
